# Generated by Django 5.2 on 2025-04-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
                ("Name", models.CharField(max_length=50)),
                ("phone_no", models.BigIntegerField(default=100)),
                ("qualification", models.CharField(max_length=50)),
                ("college", models.CharField(max_length=100)),
            ],
        ),
    ]
