# Generated by Django 5.2 on 2025-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blearn_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=300)),
                ("option1", models.CharField(max_length=100)),
                ("option2", models.CharField(max_length=100)),
                ("option3", models.CharField(max_length=100)),
                ("option4", models.CharField(max_length=100)),
                ("correct_answer", models.CharField(max_length=100)),
            ],
        ),
    ]
