# Generated by Django 5.2.1 on 2025-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blearn_app", "0008_student_year_alter_student_phone_no_examrecording"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone_no",
            field=models.BigIntegerField(),
        ),
    ]
