# Generated by Django 5.2.1 on 2025-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blearn_app", "0009_alter_student_phone_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="year",
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_no",
            field=models.BigIntegerField(unique=True),
        ),
    ]
