# Generated by Django 5.2.1 on 2025-07-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blearn_app", "0010_remove_student_year_alter_student_phone_no"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExamRecording",
        ),
    ]
