# Generated by Django 5.2.1 on 2025-07-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blearn_app", "0011_delete_examrecording"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.CharField(
                choices=[
                    ("1st Year", "1st Year"),
                    ("2nd Year", "2nd Year"),
                    ("3rd Year", "3rd Year"),
                    ("4th Year", "4th Year"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ExamRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="recordings/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="blearn_app.result",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blearn_app.student",
                    ),
                ),
            ],
        ),
    ]
