# Generated by Django 5.2.1 on 2025-07-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blearn_app", "0012_student_year_examrecording"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="back_paper_details",
            field=models.CharField(
                blank=True,
                help_text="Mention details if not completed.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="interested_course",
            field=models.CharField(
                choices=[
                    ("Data Science", "Data Science"),
                    ("Data Analytics", "Data Analytics"),
                    ("Cloud Computing", "Cloud Computing"),
                    ("Cyber Security", "Cyber Security"),
                    ("Networking", "Networking"),
                    ("Python Fullstack", "Python Fullstack"),
                    ("MERN Stack", "MERN Stack"),
                    ("Java Fullstack", "Java Fullstack"),
                    ("Flutter", "Flutter"),
                    ("Software Testing", "Software Testing"),
                    ("DevOps", "DevOps"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="year",
            field=models.CharField(
                choices=[
                    ("1st Year", "1st Year"),
                    ("2nd Year", "2nd Year"),
                    ("3rd Year", "3rd Year"),
                    ("4th Year", "4th Year"),
                    ("Graduated", "Graduated"),
                    ("Not Completed", "Not Completed"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
