# Generated by Django 5.2.1 on 2025-07-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blearn_app", "0013_student_back_paper_details_student_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="back_paper_details",
        ),
    ]
